---
- :key: author
  :value: complex
  :input_type: radio
  :possible_values: '["simple","complex"]'
- :key: tag
  :value: 'true'
  :input_type: boolean
  :possible_values: '[true, false]'
- :key: related_story
  :value: theme
  :input_type: radio
  :possible_values: '["empty","theme"]'
- :key: category_publishable
  :value: 'true'
  :input_type: boolean
  :possible_values: "[true,false]"
